### ISSUE TITLE
Favicon fetchOnly displays wrong string

### ISSUE THREAD

**Issue by StanMenten99** [stefanbauer/laravel-favicon-extractor#10]
Hi,

I get this output from fetchOnly
`
�PNG  IHDR(-SsBIT��O�9PLTE� �,�+�+�,�,�,GpL�,��+�+�+�)�"�*�,�,�,�OtRNS �
` 

Below my code;
`
$favicon = StefanBauer\LaravelFaviconExtractor\Facades\FaviconExtractor::fromUrl('https://laravel.com')->fetchOnly();
echo $favicon->getContent();
`

**Comment by stefanbauer** [comment]
That's totally right. You fetched it, and you get the raw content of that png in this case. You need to do whatever you want to. Save it to a file or send the responsible header with the content above.

What's your expectation?

**Comment by StanMenten99** [comment]
My bad, I expected a PNG as return.
